//
//  studentListDetailPresenter.swift
//  MVPTest
//
//  Created by user on 7.11.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol studentListDetailPresentationLogic
{
  func presentSomething(response: studentListDetail.Something.Response)
}

class studentListDetailPresenter: studentListDetailPresentationLogic
{
  weak var viewController: studentListDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: studentListDetail.Something.Response)
  {
    let viewModel = studentListDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
