//
//  studentListDetailInteractor.swift
//  MVPTest
//
//  Created by user on 7.11.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol studentListDetailBusinessLogic
{
  func doSomething(request: studentListDetail.Something.Request)
}

protocol studentListDetailDataStore
{
  //var name: String { get set }
}

class studentListDetailInteractor: studentListDetailBusinessLogic, studentListDetailDataStore
{
  var presenter: studentListDetailPresentationLogic?
  var worker: studentListDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: studentListDetail.Something.Request)
  {
    worker = studentListDetailWorker()
    worker?.doSomeWork()
    
    let response = studentListDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
